name: GUIShop
main: com.pablo67340.guishop.main.Main
version: 7.0B
author: pablo67340
description: Shop Plugin for any server.
depend: [Vault]
softdepend: [SilkSpawners, EpicSpawners]
api-version: 1.13
permissions:
    guishop.use:
        default: false
        description: Grants access to GUIShop
    guishop.slot.*:
        default: false
        description: Grants access to specific items in shop
    guishop.reload:
        default: false
        description: Grants access to reload shops
    guishop.creator:
        default: false
        description: Grants access to GUIShop Creator